/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.data.elastic.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DateInterval extends org.apache.thrift.TUnion<DateInterval, DateInterval._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DateInterval");
  private static final org.apache.thrift.protocol.TField CUSTOM_INTERVAL_FIELD_DESC = new org.apache.thrift.protocol.TField("customInterval", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField STATIC_INTERVAL_FIELD_DESC = new org.apache.thrift.protocol.TField("staticInterval", org.apache.thrift.protocol.TType.I32, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CUSTOM_INTERVAL((short)1, "customInterval"),
    /**
     * 
     * @see DateIntervalType
     */
    STATIC_INTERVAL((short)2, "staticInterval");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CUSTOM_INTERVAL
          return CUSTOM_INTERVAL;
        case 2: // STATIC_INTERVAL
          return STATIC_INTERVAL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CUSTOM_INTERVAL, new org.apache.thrift.meta_data.FieldMetaData("customInterval", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STATIC_INTERVAL, new org.apache.thrift.meta_data.FieldMetaData("staticInterval", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, DateIntervalType.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DateInterval.class, metaDataMap);
  }

  public DateInterval() {
    super();
  }

  public DateInterval(_Fields setField, Object value) {
    super(setField, value);
  }

  public DateInterval(DateInterval other) {
    super(other);
  }
  public DateInterval deepCopy() {
    return new DateInterval(this);
  }

  public static DateInterval customInterval(String value) {
    DateInterval x = new DateInterval();
    x.setCustomInterval(value);
    return x;
  }

  public static DateInterval staticInterval(DateIntervalType value) {
    DateInterval x = new DateInterval();
    x.setStaticInterval(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case CUSTOM_INTERVAL:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field 'customInterval', but got " + value.getClass().getSimpleName());
      case STATIC_INTERVAL:
        if (value instanceof DateIntervalType) {
          break;
        }
        throw new ClassCastException("Was expecting value of type DateIntervalType for field 'staticInterval', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case CUSTOM_INTERVAL:
          if (field.type == CUSTOM_INTERVAL_FIELD_DESC.type) {
            String customInterval;
            customInterval = iprot.readString();
            return customInterval;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case STATIC_INTERVAL:
          if (field.type == STATIC_INTERVAL_FIELD_DESC.type) {
            DateIntervalType staticInterval;
            staticInterval = DateIntervalType.findByValue(iprot.readI32());
            return staticInterval;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CUSTOM_INTERVAL:
        String customInterval = (String)value_;
        oprot.writeString(customInterval);
        return;
      case STATIC_INTERVAL:
        DateIntervalType staticInterval = (DateIntervalType)value_;
        oprot.writeI32(staticInterval.getValue());
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case CUSTOM_INTERVAL:
          String customInterval;
          customInterval = iprot.readString();
          return customInterval;
        case STATIC_INTERVAL:
          DateIntervalType staticInterval;
          staticInterval = DateIntervalType.findByValue(iprot.readI32());
          return staticInterval;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CUSTOM_INTERVAL:
        String customInterval = (String)value_;
        oprot.writeString(customInterval);
        return;
      case STATIC_INTERVAL:
        DateIntervalType staticInterval = (DateIntervalType)value_;
        oprot.writeI32(staticInterval.getValue());
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case CUSTOM_INTERVAL:
        return CUSTOM_INTERVAL_FIELD_DESC;
      case STATIC_INTERVAL:
        return STATIC_INTERVAL_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public String getCustomInterval() {
    if (getSetField() == _Fields.CUSTOM_INTERVAL) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'customInterval' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setCustomInterval(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.CUSTOM_INTERVAL;
    value_ = value;
  }

  /**
   * 
   * @see DateIntervalType
   */
  public DateIntervalType getStaticInterval() {
    if (getSetField() == _Fields.STATIC_INTERVAL) {
      return (DateIntervalType)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'staticInterval' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  /**
   * 
   * @see DateIntervalType
   */
  public void setStaticInterval(DateIntervalType value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.STATIC_INTERVAL;
    value_ = value;
  }

  public boolean isSetCustomInterval() {
    return setField_ == _Fields.CUSTOM_INTERVAL;
  }


  public boolean isSetStaticInterval() {
    return setField_ == _Fields.STATIC_INTERVAL;
  }


  public boolean equals(Object other) {
    if (other instanceof DateInterval) {
      return equals((DateInterval)other);
    } else {
      return false;
    }
  }

  public boolean equals(DateInterval other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(DateInterval other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    HashCodeBuilder hcb = new HashCodeBuilder();
    hcb.append(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      hcb.append(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        hcb.append(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        hcb.append(value);
      }
    }
    return hcb.toHashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
