/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.data.elastic.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DateField extends org.apache.thrift.TUnion<DateField, DateField._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DateField");
  private static final org.apache.thrift.protocol.TField _FIELD_FIELD_DESC = new org.apache.thrift.protocol.TField("_field", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField KEY_VALUE_DATE_FIELD_FIELD_DESC = new org.apache.thrift.protocol.TField("keyValueDateField", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField KEY_VALUE_DATE_SCRIPT_FIELD_DESC = new org.apache.thrift.protocol.TField("keyValueDateScript", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    _FIELD((short)1, "_field"),
    KEY_VALUE_DATE_FIELD((short)2, "keyValueDateField"),
    KEY_VALUE_DATE_SCRIPT((short)3, "keyValueDateScript");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // _FIELD
          return _FIELD;
        case 2: // KEY_VALUE_DATE_FIELD
          return KEY_VALUE_DATE_FIELD;
        case 3: // KEY_VALUE_DATE_SCRIPT
          return KEY_VALUE_DATE_SCRIPT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields._FIELD, new org.apache.thrift.meta_data.FieldMetaData("_field", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.KEY_VALUE_DATE_FIELD, new org.apache.thrift.meta_data.FieldMetaData("keyValueDateField", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, KeyValueFacet.class)));
    tmpMap.put(_Fields.KEY_VALUE_DATE_SCRIPT, new org.apache.thrift.meta_data.FieldMetaData("keyValueDateScript", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, KeyValueDateScript.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DateField.class, metaDataMap);
  }

  public DateField() {
    super();
  }

  public DateField(_Fields setField, Object value) {
    super(setField, value);
  }

  public DateField(DateField other) {
    super(other);
  }
  public DateField deepCopy() {
    return new DateField(this);
  }

  public static DateField _field(String value) {
    DateField x = new DateField();
    x.set_field(value);
    return x;
  }

  public static DateField keyValueDateField(KeyValueFacet value) {
    DateField x = new DateField();
    x.setKeyValueDateField(value);
    return x;
  }

  public static DateField keyValueDateScript(KeyValueDateScript value) {
    DateField x = new DateField();
    x.setKeyValueDateScript(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case _FIELD:
        if (value instanceof String) {
          break;
        }
        throw new ClassCastException("Was expecting value of type String for field '_field', but got " + value.getClass().getSimpleName());
      case KEY_VALUE_DATE_FIELD:
        if (value instanceof KeyValueFacet) {
          break;
        }
        throw new ClassCastException("Was expecting value of type KeyValueFacet for field 'keyValueDateField', but got " + value.getClass().getSimpleName());
      case KEY_VALUE_DATE_SCRIPT:
        if (value instanceof KeyValueDateScript) {
          break;
        }
        throw new ClassCastException("Was expecting value of type KeyValueDateScript for field 'keyValueDateScript', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case _FIELD:
          if (field.type == _FIELD_FIELD_DESC.type) {
            String _field;
            _field = iprot.readString();
            return _field;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case KEY_VALUE_DATE_FIELD:
          if (field.type == KEY_VALUE_DATE_FIELD_FIELD_DESC.type) {
            KeyValueFacet keyValueDateField;
            keyValueDateField = new KeyValueFacet();
            keyValueDateField.read(iprot);
            return keyValueDateField;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case KEY_VALUE_DATE_SCRIPT:
          if (field.type == KEY_VALUE_DATE_SCRIPT_FIELD_DESC.type) {
            KeyValueDateScript keyValueDateScript;
            keyValueDateScript = new KeyValueDateScript();
            keyValueDateScript.read(iprot);
            return keyValueDateScript;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case _FIELD:
        String _field = (String)value_;
        oprot.writeString(_field);
        return;
      case KEY_VALUE_DATE_FIELD:
        KeyValueFacet keyValueDateField = (KeyValueFacet)value_;
        keyValueDateField.write(oprot);
        return;
      case KEY_VALUE_DATE_SCRIPT:
        KeyValueDateScript keyValueDateScript = (KeyValueDateScript)value_;
        keyValueDateScript.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case _FIELD:
          String _field;
          _field = iprot.readString();
          return _field;
        case KEY_VALUE_DATE_FIELD:
          KeyValueFacet keyValueDateField;
          keyValueDateField = new KeyValueFacet();
          keyValueDateField.read(iprot);
          return keyValueDateField;
        case KEY_VALUE_DATE_SCRIPT:
          KeyValueDateScript keyValueDateScript;
          keyValueDateScript = new KeyValueDateScript();
          keyValueDateScript.read(iprot);
          return keyValueDateScript;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case _FIELD:
        String _field = (String)value_;
        oprot.writeString(_field);
        return;
      case KEY_VALUE_DATE_FIELD:
        KeyValueFacet keyValueDateField = (KeyValueFacet)value_;
        keyValueDateField.write(oprot);
        return;
      case KEY_VALUE_DATE_SCRIPT:
        KeyValueDateScript keyValueDateScript = (KeyValueDateScript)value_;
        keyValueDateScript.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case _FIELD:
        return _FIELD_FIELD_DESC;
      case KEY_VALUE_DATE_FIELD:
        return KEY_VALUE_DATE_FIELD_FIELD_DESC;
      case KEY_VALUE_DATE_SCRIPT:
        return KEY_VALUE_DATE_SCRIPT_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public String get_field() {
    if (getSetField() == _Fields._FIELD) {
      return (String)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field '_field' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void set_field(String value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields._FIELD;
    value_ = value;
  }

  public KeyValueFacet getKeyValueDateField() {
    if (getSetField() == _Fields.KEY_VALUE_DATE_FIELD) {
      return (KeyValueFacet)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'keyValueDateField' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setKeyValueDateField(KeyValueFacet value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.KEY_VALUE_DATE_FIELD;
    value_ = value;
  }

  public KeyValueDateScript getKeyValueDateScript() {
    if (getSetField() == _Fields.KEY_VALUE_DATE_SCRIPT) {
      return (KeyValueDateScript)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'keyValueDateScript' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setKeyValueDateScript(KeyValueDateScript value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.KEY_VALUE_DATE_SCRIPT;
    value_ = value;
  }

  public boolean isSet_field() {
    return setField_ == _Fields._FIELD;
  }


  public boolean isSetKeyValueDateField() {
    return setField_ == _Fields.KEY_VALUE_DATE_FIELD;
  }


  public boolean isSetKeyValueDateScript() {
    return setField_ == _Fields.KEY_VALUE_DATE_SCRIPT;
  }


  public boolean equals(Object other) {
    if (other instanceof DateField) {
      return equals((DateField)other);
    } else {
      return false;
    }
  }

  public boolean equals(DateField other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(DateField other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    HashCodeBuilder hcb = new HashCodeBuilder();
    hcb.append(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      hcb.append(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        hcb.append(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        hcb.append(value);
      }
    }
    return hcb.toHashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
